# **Part 1: Exercise Numpy**

## **Jangan di-run! Save sebagai file baru dan edit file tersebut untuk menjawab pertanyaan**

In [2]:
import numpy as np
import pandas as pd

<hr>

### **Nomor 1**

Buatlah sebuah array 1D dengan nama variable myArray yang terdiri dari 36 angka bilangan bulat acak antara 1 dan 100! (Gunakan seed=0)

In [3]:
myArray = np.random.randint(1, 100, 36)
myArray

array([44, 64, 77, 14, 55, 93, 61,  9, 60, 43, 31, 84, 46, 15, 48, 82, 44,
       89, 42, 26, 62, 82, 74, 58, 55, 44, 95, 72, 89, 47, 57, 58, 62, 63,
       84, 51])

<hr>

### **Nomor 2**

Ubahlah array tersebut (myArray) menjadi

* array 2D dengan ukuran 2 x 18
* array 2D dengan ukuran 9 x 4
* array 3D dengan ukuran 2 x 6 X 3

In [4]:
myArray.reshape(2, 18)

array([[44, 64, 77, 14, 55, 93, 61,  9, 60, 43, 31, 84, 46, 15, 48, 82,
        44, 89],
       [42, 26, 62, 82, 74, 58, 55, 44, 95, 72, 89, 47, 57, 58, 62, 63,
        84, 51]])

In [5]:
myArray.reshape(9, 4)

array([[44, 64, 77, 14],
       [55, 93, 61,  9],
       [60, 43, 31, 84],
       [46, 15, 48, 82],
       [44, 89, 42, 26],
       [62, 82, 74, 58],
       [55, 44, 95, 72],
       [89, 47, 57, 58],
       [62, 63, 84, 51]])

In [6]:
myArray.reshape(2, 6, 3)

array([[[44, 64, 77],
        [14, 55, 93],
        [61,  9, 60],
        [43, 31, 84],
        [46, 15, 48],
        [82, 44, 89]],

       [[42, 26, 62],
        [82, 74, 58],
        [55, 44, 95],
        [72, 89, 47],
        [57, 58, 62],
        [63, 84, 51]]])

<hr>

### **Nomor 3**

Buatlah array baru dengan nama variable new_array yang berisi 9 angka yang diambil dari data pada index ke-3, 5, 30, 12, 15, 8, 24, 14, dan 22 dari myArray!

Ubahlah array tersebut menjadi array 2D dengan ukuran 3 x 3 secara permanen!


In [9]:
index = [3, 5, 30, 12, 15, 8, 24, 14, 22]
new_array = myArray[index]
print(new_array)

new_array = new_array.reshape(3, 3)
print(new_array)

[14 93 57 46 82 60 55 48 74]
[[14 93 57]
 [46 82 60]
 [55 48 74]]


# **Part 2: Exercise Pandas**

**Membuat DataFrame**

Ikuti semua petunjuk yang harus dilakukan di bawah ini.

### **Nomor 4**

**Buat dictionary untuk membuat DataFrame berjumlah 6 keys dan masing-masing key memiliki value berupa list dengan 10 item. Isi dari dictionary  mengikuti output Nomor 5.**

In [7]:
data_dict = {
    'Nama': ['Andi', 'Budi', 'Caca', 'Dedi', 'Erika', 'Fahri', 'Gina', 'Hani', 'Indro', 'Jarot'],
    'Gender': ['Pria', 'Pria', 'Wanita', 'Pria', 'Wanita', 'Pria', 'Wanita', 'Wanita', 'Pria', 'Pria'],
    'Umur': [24, 25, 30, 32, 28, 24, 29, 31, 30, 29],
    'Domisili': ['Jakarta', 'Tangerang Selatan', 'Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Yogyakarta', 'Jakarta', 'Tangerang Selatan'],
    'Pekerjaan': ['Data Analyst', 'Data Engineer', 'Data Scientist', 'Data Scientist', 'Data Analyst', 'Data Engineer', 'ML Engineer', 'ML Researcher', 'BI Analyst', 'Data Analyst'],
    'Hobi': ['Gaming', 'Futsal', 'Baca', 'Gaming', 'Masak', 'Traveling', 'Basket', 'Traveling', 'Gaming', 'Futsal']
}

### **Nomor 5**

**Ubah dictionary dari Nomor 4 menjadi bentuk DataFrame dan simpan ke dalam variabel baru bernama `df`.**

In [8]:
df = pd.DataFrame(data_dict)
df

Nama  Gender  Umur           Domisili       Pekerjaan       Hobi
0   Andi    Pria    24            Jakarta    Data Analyst     Gaming
1   Budi    Pria    25  Tangerang Selatan   Data Engineer     Futsal
2   Caca  Wanita    30            Jakarta  Data Scientist       Baca
3   Dedi    Pria    32            Bandung  Data Scientist     Gaming
4  Erika  Wanita    28            Jakarta    Data Analyst      Masak
5  Fahri    Pria    24           Surabaya   Data Engineer  Traveling
6   Gina  Wanita    29            Bandung     ML Engineer     Basket
7   Hani  Wanita    31         Yogyakarta   ML Researcher  Traveling
8  Indro    Pria    30            Jakarta      BI Analyst     Gaming
9  Jarot    Pria    29  Tangerang Selatan    Data Analyst     Futsal

### **Nomor 6**
**Gunakan**:
- `.iloc` untuk mengambil data Dedi, Fahri, Hani
- `.loc` untuk mengambil data Dedi, Fahri, Hani

Nama  Gender  Umur    Domisili       Pekerjaan
3   Dedi    Pria    32     Bandung  Data Scientist
5  Fahri    Pria    24    Surabaya   Data Engineer
7   Hani  Wanita    31  Yogyakarta   ML Researcher

### **Nomor 7**
**Gunakan**:
- `loc`  untuk menampilkan domisili dan pekerjaan dari Caca dan Indro
- `iloc` untuk menampilkan domisili dan pekerjaan dari Caca dan Indro

In [11]:
#iloc





### **Nomor 8**
Tampilkan semua data yang berumur dibawah 30 tahun

In [16]:
kondisi = df["Umur"] < 30
df[kondisi]

Nama  Gender  Umur           Domisili      Pekerjaan       Hobi
0   Andi    Pria    24            Jakarta   Data Analyst     Gaming
1   Budi    Pria    25  Tangerang Selatan  Data Engineer     Futsal
4  Erika  Wanita    28            Jakarta   Data Analyst      Masak
5  Fahri    Pria    24           Surabaya  Data Engineer  Traveling
6   Gina  Wanita    29            Bandung    ML Engineer     Basket
9  Jarot    Pria    29  Tangerang Selatan   Data Analyst     Futsal

**9. Siapa sajakah yang berumur lebih dari 29 tahun dan hobinya Gaming?**

In [18]:
kondisi = df["Umur"] > 29
df[kondisi]

Nama  Gender  Umur    Domisili       Pekerjaan       Hobi
2   Caca  Wanita    30     Jakarta  Data Scientist       Baca
3   Dedi    Pria    32     Bandung  Data Scientist     Gaming
7   Hani  Wanita    31  Yogyakarta   ML Researcher  Traveling
8  Indro    Pria    30     Jakarta      BI Analyst     Gaming